import { DailyColor } from '@/data/colors/schema';

export const DAILY_COLORS: DailyColor[] = [
  {
    index: 1,
    nameKo: '팥죽빛',
    nameEn: 'Red Bean Porridge',
    description: '동지날 따뜻하게 끓인 팥죽의 깊고 붉은 빛깔',
    division: '빨강계',
    category: '음식',
    hex: '#733738',
    rgb: { r: 115, g: 55, b: 56 },
    cmyk: { c: 0, m: 52, y: 51, k: 55 },
    munsell: '5R 3/6',
  },
  {
    index: 2,
    nameKo: '겨울밤빛',
    nameEn: 'Winter Night Blue',
    description: '고요한 겨울밤, 깊은 하늘의 색',
    division: '남색계',
    category: '시간',
    hex: '#1B2838',
    rgb: { r: 27, g: 40, b: 56 },
    cmyk: { c: 52, m: 29, y: 0, k: 78 },
    munsell: '5PB 2/4',
  },
  {
    index: 3,
    nameKo: '동백빛',
    nameEn: 'Camellia Red',
    description: '눈 속에서도 피어나는 동백의 붉은 기품',
    division: '빨강계',
    category: '식물',
    hex: '#C41E3A',
    rgb: { r: 196, g: 30, b: 58 },
    cmyk: { c: 0, m: 85, y: 70, k: 23 },
    munsell: '5R 4/14',
  },
  {
    index: 4,
    nameKo: '새벽안개빛',
    nameEn: 'Dawn Mist Gray',
    description: '동이 트기 전, 산을 감싸는 부드러운 안개',
    division: '회색계',
    category: '시간',
    hex: '#B8C4C8',
    rgb: { r: 184, g: 196, b: 200 },
    cmyk: { c: 8, m: 2, y: 0, k: 22 },
    munsell: '5B 8/1',
  },
  {
    index: 5,
    nameKo: '소나무빛',
    nameEn: 'Pine Green',
    description: '한겨울에도 푸르른 소나무의 기개',
    division: '초록계',
    category: '식물',
    hex: '#2D5A3D',
    rgb: { r: 45, g: 90, b: 61 },
    cmyk: { c: 50, m: 0, y: 32, k: 65 },
    munsell: '10GY 3/6',
  },
  {
    index: 6,
    nameKo: '호박엿빛',
    nameEn: 'Pumpkin Taffy Gold',
    description: '정월의 달콤한 호박엿, 황금빛 투명함',
    division: '노랑계',
    category: '음식',
    hex: '#E8A317',
    rgb: { r: 232, g: 163, b: 23 },
    cmyk: { c: 0, m: 30, y: 90, k: 9 },
    munsell: '10YR 7/12',
  },
  {
    index: 7,
    nameKo: '까치깃빛',
    nameEn: 'Magpie Feather Black',
    description: '새해 소식 전하는 까치의 윤기 나는 깃털',
    division: '검정계',
    category: '동물',
    hex: '#1C1C1C',
    rgb: { r: 28, g: 28, b: 28 },
    cmyk: { c: 0, m: 0, y: 0, k: 89 },
    munsell: 'N 1.5/',
  },
  {
    index: 8,
    nameKo: '청자빛',
    nameEn: 'Celadon Blue',
    description: '고려청자의 은은하고 깊은 비색',
    division: '청록계',
    category: '생활',
    hex: '#7BA3A8',
    rgb: { r: 123, g: 163, b: 168 },
    cmyk: { c: 27, m: 3, y: 0, k: 34 },
    munsell: '5BG 6/4',
  },
  {
    index: 9,
    nameKo: '곶감빛',
    nameEn: 'Dried Persimmon Orange',
    description: '처마 끝에 매달린 곶감의 깊은 주황',
    division: '주황계',
    category: '음식',
    hex: '#D35400',
    rgb: { r: 211, g: 84, b: 0 },
    cmyk: { c: 0, m: 60, y: 100, k: 17 },
    munsell: '2.5YR 5/14',
  },
  {
    index: 10,
    nameKo: '서리빛',
    nameEn: 'Frost Silver',
    description: '아침 창가에 내린 하얀 서리의 결정',
    division: '흰색계',
    category: '자연현상',
    hex: '#E8E8E8',
    rgb: { r: 232, g: 232, b: 232 },
    cmyk: { c: 0, m: 0, y: 0, k: 9 },
    munsell: 'N 9/',
  },
  {
    index: 11,
    nameKo: '잿빛하늘',
    nameEn: 'Ash Sky Gray',
    description: '눈 오기 전, 낮게 드리운 겨울 하늘',
    division: '회색계',
    category: '자연현상',
    hex: '#6B7B8C',
    rgb: { r: 107, g: 123, b: 140 },
    cmyk: { c: 24, m: 12, y: 0, k: 45 },
    munsell: '5PB 5/3',
  },
  {
    index: 12,
    nameKo: '매화빛',
    nameEn: 'Plum Blossom Pink',
    description: '추위를 이기고 피어난 매화의 수줍은 분홍',
    division: '분홍계',
    category: '식물',
    hex: '#F4C2C2',
    rgb: { r: 244, g: 194, b: 194 },
    cmyk: { c: 0, m: 21, y: 21, k: 4 },
    munsell: '5R 8/4',
  },
  {
    index: 13,
    nameKo: '황토빛',
    nameEn: 'Yellow Earth Brown',
    description: '따스한 온돌 아래, 흙의 정기를 품은 색',
    division: '갈색계',
    category: '광물',
    hex: '#C49A6C',
    rgb: { r: 196, g: 154, b: 108 },
    cmyk: { c: 0, m: 21, y: 45, k: 23 },
    munsell: '10YR 6/6',
  },
  {
    index: 14,
    nameKo: '자수정빛',
    nameEn: 'Amethyst Purple',
    description: '겨울 산사의 고요함을 담은 보랏빛 수정',
    division: '보라계',
    category: '광물',
    hex: '#9966CC',
    rgb: { r: 153, g: 102, b: 204 },
    cmyk: { c: 25, m: 50, y: 0, k: 20 },
    munsell: '5P 5/10',
  },
];

export const COLOR_DIVISIONS = [
  '빨강계',
  '주황계',
  '노랑계',
  '연두계',
  '초록계',
  '청록계',
  '파랑계',
  '남색계',
  '보라계',
  '자주계',
  '분홍계',
  '갈색계',
  '흰색계',
  '회색계',
  '검정계',
] as const;

export const COLOR_CATEGORIES = [
  '동물',
  '식물',
  '자연현상',
  '광물',
  '음식',
  '생활',
  '감정',
  '계절',
  '시간',
] as const;
